@baseUrl = http://localhost:5050
@authToken = {{Authenticate.response.body.$.access_token}}

# @name Create_Account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Felipe Sakai",
  "email": "felipeSakai@example.com",
  "password": "123456"
}

### 

# @name Authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "felipeSakai@example.com",
  "password": "123456"
}

###

# @name Create_Question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Minha pergunta",
  "content": "Conteudo da pergunta"
}
